version: '2'

services:    
    bf_load_article:
        image: apfelpresse/grafanamon_pythonbase:latest
        container_name: bf_load_article
        restart:
            always
        mem_limit: 50M
        hostname: ${HOST_NAME}
        volumes:
            - ./app:/app
        environment:
            - MONGO_HOST=${MONGO_HOST}
            - GRAPHITE_SERVER=${GRAPHITE_HOST}
            - GRAPHITE_PORT=${GRAPHITE_PORT}
            - PROXY_HOST=${PROXY_HOST}