version: '2'

services:    
    hb_load_article:
        container_name: hb_load_article
        build: .
        restart:
            always
        mem_limit: 50M
        hostname: ${HOST_NAME}
        environment:
            - MONGO_HOST=${MONGO_HOST}
            - GRAPHITE_SERVER=${GRAPHITE_HOST}
            - GRAPHITE_PORT=${GRAPHITE_PORT}
            - PROXY_HOST=${PROXY_HOST}