version: '2'

services:
  
    grafana:
        image: grafana/grafana
        restart: always
        ports:
            - 100:3000
        environment:
            GF_RENDERING_SERVER_URL: http://renderer:8081/render
            GF_RENDERING_CALLBACK_URL: http://grafana:3000/
            GF_LOG_FILTERS: rendering:debug
        volumes: 
            - grafana_data:/var/lib/grafana
            - grafana_datasources:/etc/grafana/provisioning/datasources
            - grafana_dashboards:/etc/grafana/provisioning/dashboards
      
    renderer:
        image: grafana/grafana-image-renderer
        restart: always
        environment:
            ENABLE_METRICS: 'true'
  
    graphite:
        image: sitespeedio/graphite
        ports:
            - 12000:2003
        volumes:
            - ./storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
    
volumes:
    grafana_data: {}
    grafana_datasources: {}
    grafana_dashboards: {}