version: '2'

services:
  
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        environment:
            GF_RENDERING_SERVER_URL: http://renderer:8081/render
            GF_RENDERING_CALLBACK_URL: http://grafana:3000/
            GF_LOG_FILTERS: rendering:debug
            GF_INSTALL_PLUGINS: grafana-clock-panel,flant-statusmap-panel,vonage-status-panel
        depends_on:
            - renderer
        volumes: 
            - grafana_data:/var/lib/grafana
            - grafana_datasources:/etc/grafana/provisioning/datasources
            - grafana_dashboards:/etc/grafana/provisioning/dashboards
        mem_limit: 300M
              
    renderer:
        image: grafana/grafana-image-renderer
        container_name: grafana-renderer
        restart: always
        environment:
            ENABLE_METRICS: 'true'
        mem_limit: 80M
              
    graphite:
        image: sitespeedio/graphite
        container_name: graphite_container
        ports:
            - 10.0.0.3:2003:2003
        volumes:
            - ./storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        mem_limit: 1G
              
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./default:/config/nginx/site-confs/default
            - letsencrypt_etc:/etc
        restart:
            always
        depends_on:
            - grafana
            - graphite
        environment:
            - PUID=1050
            - PGID=1050
            - EMAIL=analogwurst-1@yahoo.de
            - ONLY_SUBDOMAINS=true
            - SUBDOMAINS=dash
            - URL=stiefels.biz
            - TZ=Europe/Berlin
            - STAGING=false
        mem_limit: 100M

    graphitecollectd:
        image: pboos/collectd-graphite
        container_name: sys-stats
        privileged: true
        restart:
            always
        volumes:
            - /:/hostfs:ro
        depends_on:
            - graphite
        network_mode: host
        environment:
            - HOST_NAME=monitoring
            - GRAPHITE_HOST=10.0.0.3
        mem_limit: 10M
    
    docker_stats:
        container_name: docker-stats
        build: ./docker_stats/
        hostname: monitoring
        restart:
            always
        volumes:
           - /var/run/docker.sock:/var/run/docker.sock
        environment:
           - GRAPHITE_SERVER=10.0.0.3
        mem_limit: 50M
    
volumes:
    grafana_data: {}
    grafana_datasources: {}
    grafana_dashboards: {}
    letsencrypt_etc: {}