version: "2"

services:
  docker_stats:
    container_name: docker_stats
    build: .
    restart:
        always
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
       - 2003:2003
    environment:
       - GRAPHITE_SERVER=${GRAPHITE_HOST}