version: '2'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - /mnt/HC_Volume_7680431/db:/data/db
    ports:
      - ${MONGO_HOST}:27017-27019:27017-27019    
    mem_limit: 1gb
    
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoexp
    ports:
      - ${MONGO_HOST}:8081:8081
    mem_limit: 100mb
networks:
    mongonet:
        driver: bridge
    