version: '2'

services:    
    yahoo_finance:
        container_name: yahoo_finance
        build: .
        restart:
            always
        mem_limit: 50M
        hostname: ${HOST_NAME}
        environment:
            - MONGO_HOST=${MONGO_HOST}
            - GRAPHITE_SERVER=${GRAPHITE_HOST}
            - GRAPHITE_PORT=${GRAPHITE_PORT}
            - PROXY_HOST=${PROXY_HOST}