version: "2.4"
services:
  proxy:
    image: qmcgaw/private-internet-access
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
        - 10.0.0.5:9000-9009:8888/tcp
    environment:
      - VPNSP=Surfshark
      - OPENVPN_USER=${user}
      - PASSWORD=${pass}
      - HTTPPROXY=ON
    networks:
      - lbnet
    scale: 10
    mem_limit: 100mb    

networks:
  lbnet:
    external: true
    name: lbnet
