version: "3.7"
services:
  proxy:
    image: qmcgaw/private-internet-access
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    #ports:
    #  - 8888/tcp
    restart: always
    volumes:
      - /yourpath:/gluetun
    environment:
      - VPNSP=Surfshark
      - USER=$USER
      - PASSWORD=$PASSWORD
      - HTTPPROXY=ON
    mem_limit: 100M
    networks:
        - lbnet

networks:
  lbnet:
    external: true



