version: '2.4'

services:
    nginx: 
        image: nginx:latest
        container_name: nginx_proxy
        volumes:
          - ./default:/config/nginx/site-confs/default
        ports:
          - loadbalancer:9000:80
        networks:
            - lbnet

networks:
  lbnet:
    external: true
    name: lbnet