version: '2'

services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./default:/config/nginx/site-confs/default
            - letsencrypt_etc:/etc/
            - letsencrypt_var:/var/
        restart:
            always
        environment:
            - PUID=1050
            - PGID=1050
            - EMAIL=analogwurst-1@yahoo.de
            - ONLY_SUBDOMAINS=true
            - SUBDOMAINS=api
            - URL=stiefels.biz
            - TZ=Europe/Berlin
            - STAGING=true
        mem_limit: 100M
        networks:
            - lbnet

networks:
  lbnet:
    external: true

volumes:
    letsencrypt_etc: {}
    letsencrypt_var: {}