version: '2'

services:    
    bf_load_news_text:
        container_name: bf_load_news_text
        build: .
        restart:
            always
        mem_limit: 50M
        hostname: ${HOSTNAME}
        environment:
            - MONGO_HOST=${MONGO_HOST}
            - GRAPHITE_SERVER=${GRAPHITE_HOST}
            - GRAPHITE_PORT=${GRAPHITE_PORT}