version: '2'

services:    
    bf_load_news_text:
        container_name: bf_load_news_text
        build: .
        restart:
            always
        mem_limit: 50M
        hostname: ${HOSTNAME}
        env_file: ./../../../.env
        environment:
            - MONGO_HOST=${MONGO_HOST}
            - USERNAME=${MONGO_USERNAME}
            - PASSWORD=${MONGO_PASSWORD}
            - GRAPHITE_SERVER=${GRAPHITE_SERVER}
            - GRAPHITE_PORT=${GRAPHITE_PORT}